### ISSUE TITLE
Forslag til organisering av virksomhetsspesifikke metadata

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#61]
For å lagre virksomhetsspesifikke metadata kan vi lage en array som inneholder key-value elementer. Med denne strukturen vil vi ha en meget fleksibel løsning. Nøklene bør organiseres hierarkisk f.eks. med kolon som skilletegn, da vil man kunne lage et navnerom som skiller de ulike feltene. Sektorspesifikke metadata bør samles under det samme navnerommet. 

Eksempel på saksmappe med virksomhetsspesifikke metadata for PPT-fagområdet

**GET /api/sakarkiv/saksmappe/1**
```
{
    "systemID": "1",
    "tittel": "saksmappe 1",
    "virksomhetsspesifikkeMetadata": [
        { "ppt:v1:henvisningdato": "2018-04-22T13:30:00" },
        { "ppt:v1:skoleaar": "2018" }
    ]
}
```

For å kunne støtte ekstra felter som et fagsystem ønsker å lagre i virksomhetsspesfikkemetadata, så kan man benytte vendor-prefiks f. eks.: vnd:nikita:eksempelfelt. 

**GET /api/sakarkiv/saksmappe/1**
```
{
    "systemID": "1",
    "tittel": "saksmappe 1",
    "virksomhetsspesifikkeMetadata": [
        { "ppt:v1:henvisningdato": "2018-04-22T13:30:00" },
        { "ppt:v1:skoleaar": "2018/2019" },
        { "vnd:nikita:eksempelfelt": "ett eller annet" }    
    ]
}
```

Det bør etableres en struktur for å definere de virksomhetsspesifikke metadatafeltene. 
Forslag på struktur for å definere for et fagområde:

**GET /api/metadata/vsm-definitions/ppt:v1**
```
{
    "name": "ppt:v1",
    "description": "Felles informasjon for PPT-fagsystemer",
    "fields": [
        {
            "key": "ppt:v1:henvisningdato",
            "datatype": "datetime",
            "definition": "Dato når henvisning ble mottatt."
        },
        {
            "key": "ppt:v1:skoleaar",
            "datatype": "string",
            "definition": "Hvilket skoleår saken gjelder."
        },     
    ]
}
```

På hvert felt kan man f. eks. utvide med valideringsregler eller formateringsregler hvis dette er ønskelig.

**Comment by petterreinholdtsen** [comment]
Et alternativ til slik kolon-delte nøkler kan være å bruke relasjons-URL-er ala det som brukes i _links.  URL bør så kunne brukes til å hente mer informasjon om hva feltet betyr, ala det _links-relasjonene stort sett kan brukes til i dag.

**Comment by douzounov** [comment]
Here are some details about how business-specific metadata (BSM) is implemented in Documaster. Note that we have supported BSM for quite some time now and that we have gone through several iterations before coming up with our current solution.

To add business-specific metadata to an object in Documaster, a template of what the metadata can look like (data type, controlled vs uncontrolled values, etc.) must be defined in a special registry first. This is to ensure good data quality in our system especially for controlled vocabularies.

Any user with the right permissions in the system is allowed to manage the business-specific metadata registry, i.e. to create `BSM fields` and group them logically into `BSM groups` (this logical separation is required mainly due to the different needs of different departments in the same organization and does not add significant complexity when it comes to implementation).

A BSM group has:

- human-readable group identifier (that can be reused across organizations if needed)
- name
- description

A BSM field has:

- human-readable field identifier (that can be reused across organizations if needed)
- name
- description
- data type
  - string
  - integer
  - decimal
  - date
  - controlled string list
  - controlled integer list
  - controlled decimal list

Note that all fields can be single- or multi-valued.

![bsm](https://user-images.githubusercontent.com/1561331/51690546-94804080-2001-11e9-91b5-fe3613f9ddcc.png)

Have a look here to see how the BSM registry in Documaster is managed via web services:

https://github.com/documaster/noark5-web-services/blob/develop/src/04%20-%20Web%20services.md#business-specific-metadata-management-web-services

This is how BSM is returned when searching for objects:

https://github.com/documaster/noark5-web-services/blob/develop/src/04%20-%20Web%20services.md#query

And this shows how BSM is stored in objects:

https://github.com/documaster/noark5-web-services/blob/develop/src/04%20-%20Web%20services.md#save

The one thing we have not implemented in our public API yet (although we support it internally) is querying and specifying criteria on BSM fields. We will do that soon and also intend to make all business-specific metadata searchable in a full-text search service too.

I hope this information is helpful in some way.

**Comment by hanber** [comment]
Vi går for kolon-løsningen som besluttet i møtet om 7. desember 2018.

**Comment by petterreinholdtsen** [comment]
Nettopp.  Hvem formulerer utkast til spesifikasjon?  Det er antagelig lurt om det lages rutine for å registrere slike felter i et felles katalog, for å unngå navnekollisjoner.  Hvem bør i så fall vedlikeholde en slik katalog?

**Comment by petterreinholdtsen** [comment]
Nikita-prosjektet er nå igang med å formulere forslag til spesifikasjonstekst.  I den forbindelse, er det to ting jeg lurer på.  @henningjensen, hvorfor bruker du liste i stedet for ordbok i ditt eksempel?  Det kan jo enklere skrives, tolkes og brukes i javascript hvis det skrives slik:

```
"virksomhetsspesifikkeMetadata": {
        "ppt:v1:henvisningdato": "2018-04-22T13:30:00",
        "ppt:v1:skoleaar": "2018/2019",
        "vnd:nikita:eksempelfelt": "ett eller annet"
    }
```

Det andre er at når brukere av API-et skal kunne legge inn ekstra felt i mappe, registrering og sakspart, så må det være en kjent liste med felttyper som kan brukes.  Det er ingen slik liste i spesifikasjonen i dag.  Bør vi lage en egen liste med typer som kan brukes, eller henvise til en eksisterende liste med typer?

**Comment by petterreinholdtsen** [comment]
Vi i Nikita-prosjektet har formulert et forslag til formuleringer som kan tas inn i spesifikasjonen, og det er flere justeringer der i forhold til ideene og forslagene som kom i denne mangelmeldingen.  Er det noe som mangler, eller vil det løse behovet til Fredrikstad kommune?

**Comment by henningjensen** [comment]
Såvidt meg bekjent så har ikke XML noe begrep om dictionary på samme måte som JSON.  Det ble laget som en liste for å være kompatibel med XML. 

Det bør lages en liste med kjente typer - men da må noen ta på seg ansvar å forvalte denne. Arkivverket? @hanber

**Comment by petterreinholdtsen** [comment]
[Henning Jensen]
> Såvidt meg bekjent så har ikke XML noe begrep om dictionary på samme
> måte som JSON.  Det ble laget som en liste for å være kompatibel med
> XML.

Ahaq.  Jeg antar du mener XML-varianten av protokollen her, som ingen
har implementert, ingen har tatt i bruk, og som jeg på det sterkeste
anbefaler å droppe, til fordel for JSON-varianten, for å sikre at det
kun finnes ett språk API-klienter og tjenere må forstå, ikke to.

Det vil jo uansett ikke være noe problem å oversette JSON-output til XML
for API-klienter som henter ut data via API-et for deponering og
kassering.

> Det bør lages en liste med kjente typer - men da må noen ta på seg
> ansvar å forvalte denne. Arkivverket? @hanber

Som en ser i forslaget til endring som jeg laget, tilbyr
Nikita-prosjektet seg å vedlikeholde en liste over kjente typer.

Merk at dokumaster har to klasser av datatyper, en for "kontrollerte"
tekst-, heltall og desimaltallfelt, og en for "ukontrollerte" felt.
Førstnevnte vil trenge egne kodelister.  Mitt forslag inneholder de
"ukontrollerte" feltene, for enkelhets skyld.  Tenkte det kan være en
grei start, så kan vi utvide senere.

Hvis det er ønske om felt basert på kodelister, så kan jeg også
formulere litt om det i forslaget.  Det kan også formuleres senere, ser
ikke noe i strukturen på mitt forslag som skulle hindre en slik
videreutvikling.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Merk JSON-objektet kan fint representeres som XML.  Her er XML-representasjonen av JSON-objektet over:

```XML
<virksomhetsspesifikkeMetadata>
  <ppt:v1:henvisningdato>2018-04-22T13:30:00</ppt:v1:henvisningdato>
  <ppt:v1:skoleaar>2018/2019</ppt:v1:skoleaar>
  <vnd:nikita:eksempelfelt>ett eller annet</vnd:nikita:eksempelfelt>
</virksomhetsspesifikkeMetadata>
```

**Comment by petterreinholdtsen** [comment]
Ah, Thomas minnet meg på at XML ikke liker rekursive navnerom, slik at alle unntatt siste kolon må omformes til noe som kan brukes som navnerom-string.  f.eks. ala dette:

```XML
<virksomhetsspesifikkeMetadata>
  <ppt-v1:henvisningdato>2018-04-22T13:30:00</ppt:v1:henvisningdato>
  <ppt-v1:skoleaar>2018/2019</ppt:v1:skoleaar>
  <vnd-nikita:eksempelfelt>ett eller annet</vnd:nikita:eksempelfelt>
</virksomhetsspesifikkeMetadata>
```

Sjekket med https://www.w3.org/TR/xml-names/ at "-" er gyldig i navneromsnavn.  En kan bruke det meste unntatt kolon, slik jeg tolket https://www.w3.org/TR/REC-xml/#NT-NameChar .

**Comment by henningjensen** [comment]
Hvordan vil xml-skjemaet for denne strukturen se ut? Vi må pr dags dato ha et xml skjema som kan distribueres med standarden så lenge vi skal støtte XML.

**Comment by tsodring** [comment]
Tenker at noe som følgende hadde løst det:


> Filen virksomhetspesifikemetada.xsd:

```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:vnd-nikita="http://nikita.oslomet.no/felter" xmlns:ppt-v1="http://ppt-system.no/v1" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="pptsystem.xsd" namespace="http://ppt-system.no/v1" />
  <xs:import schemaLocation="nikita-felter.xsd" namespace="http://nikita.oslomet.no/felter" />
  <xs:element name="virksomhetsspesifikkeMetadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ppt-v1:henvisningdato" />
        <xs:element ref="ppt-v1:skoleaar" />
        <xs:element ref="vnd-nikita:eksempelfelt" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

> Filen pptsystem.xsd:
```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://ppt-system.no/v1" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://ppt-system.no/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="henvisningdato" type="xs:dateTime" />
  <xs:element name="skoleaar" type="xs:string" />
</xs:schema>
```

> Filen nikita-felter.xsd:
```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://nikita.oslomet.no/felter" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://nikita.oslomet.no/felter" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="eksempelfelt" type="xs:string" />
</xs:schema>
```

**Comment by petterreinholdtsen** [comment]
Nettopp.  XML-skjema for virksomhetsspesfikkemetadata genereres ut fra det som befinner seg i kodelisten med alle de definerte feltene. Gitt tilgang til APi-et vil det kanskje kreve en time å skrive et python-script som lager XML-skjema til bruk ved avlevering og deponering.  Jeg er igang med å lage et slikt script, for å sikre at en kan ha "kontinuerlig deponering" fra Nikita, slik at kostnaden rundt det tekniske ved avlevering og deponering blir minimal.

**Comment by henningjensen** [comment]
Ja, det ble en god løsning. Vi kan legge ved en tom mal på virksomhetsspesifikkemetadata.xsd slik at det er enkelt å ta i bruk. 

Vi legger dette eksemplet med i eksempelapplikasjonen også.
